// Command gocry is a command-line utility for encrypting and decrypting files using a specified key.
// It supports file encryption and line-by-line encryption based on directives within the file.
// The program outputs the processed content to standard output (stdout).
// All other informative messages are outputted to standard error (stderr).
package main

import (
	"fmt"
	"os"

	"github.com/idelchi/gocry/internal/parse"
)

// version indicates the build version, set during compilation.
var version = "unknown - unofficial & generated by unknown"

func main() {
	if err := parse.Execute(version); err != nil {
		fmt.Fprintln(os.Stderr, err.Error())

		os.Exit(1)
	}
}
