// Command gocry provides file encryption and decryption with support for both
// whole-file and line-by-line processing modes. It can be used as a standalone
// tool or integrated with git as a filter for automatic encryption/decryption.
//
// Basic usage:
//
//	gocry [flags] command [flags]
//
// The tool supports reading from stdin and writing to stdout, making it suitable
// for use in git filter pipelines. In line mode, encryption/decryption is guided
// by directives within the file content.
package main

import (
	"fmt"
	"os"

	"github.com/idelchi/gocry/internal/parse"
)

// version indicates the build version, set during compilation.
var version = "unknown - unofficial & generated by unknown"

func main() {
	if err := parse.Execute(version); err != nil {
		fmt.Fprintln(os.Stderr, err.Error())

		os.Exit(1)
	}
}
